{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ include "dot-ai.fullname" . }}
  labels:
    {{- include "dot-ai.labels" . | nindent 4 }}
  {{- $annotations := include "dot-ai.annotations" (dict "global" .Values.annotations "local" nil) -}}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ include "dot-ai.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "dot-ai.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}