apiVersion: v1
kind: Service
metadata:
  name: {{ include "yogo-ai.fullname" . }}
  labels:
    {{- include "yogo-ai.labels" . | nindent 4 }}
  {{- $annotations := include "yogo-ai.annotations" (dict "global" .Values.annotations "local" nil) -}}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "yogo-ai.selectorLabels" . | nindent 4 }}
  ports:
  - port: 3456
    targetPort: 3456
    protocol: TCP
    name: http
