{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yogo-ai.serviceAccountName" . }}
  labels:
    {{- include "yogo-ai.labels" . | nindent 4 }}
  {{- $annotations := include "yogo-ai.annotations" (dict "global" .Values.annotations "local" .Values.serviceAccount.annotations) -}}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}